# Generated by Django 4.2.25 on 2025-11-03 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('instructions', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_drops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Drop',
                'verbose_name_plural': 'Job Drops',
                'db_table': 'marketing_jobdrop',
                'ordering': ['-created_at'],
            },
        ),
    ]
