# Generated by Django 4.1.13 on 2025-11-04 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('instructions', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='media/job_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('referencing_style', models.CharField(blank=True, choices=[('apa', 'APA'), ('mla', 'MLA'), ('harvard', 'Harvard'), ('chicago', 'Chicago'), ('ieee', 'IEEE'), ('other', 'Other')], max_length=50, null=True)),
                ('writing_style', models.CharField(blank=True, choices=[('academic', 'Academic'), ('professional', 'Professional'), ('creative', 'Creative'), ('technical', 'Technical'), ('casual', 'Casual')], max_length=50, null=True)),
                ('completion_instructions', models.TextField(blank=True, null=True)),
                ('expected_deadline', models.DateTimeField(blank=True, null=True)),
                ('strict_deadline', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_completion', 'Pending Completion'), ('pending_allocation', 'Pending Allocation'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('completed_form_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketing_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='JobDrop',
        ),
    ]
