# Generated by Django 4.1.13 on 2025-11-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_job_delete_jobdrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='job_attachments/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='referencing_style',
            field=models.CharField(blank=True, choices=[('', 'Select Referencing Style'), ('apa', 'APA'), ('mla', 'MLA'), ('harvard', 'Harvard'), ('chicago', 'Chicago'), ('ieee', 'IEEE'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_completion', 'Pending Completion'), ('pending_allocation', 'Pending Allocation'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='writing_style',
            field=models.CharField(blank=True, choices=[('', 'Select Writing Style'), ('academic', 'Academic'), ('professional', 'Professional'), ('creative', 'Creative'), ('technical', 'Technical'), ('casual', 'Casual')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_id'], name='marketing_j_job_id_ebcf42_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='marketing_j_status_967ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='marketing_j_created_63a34f_idx'),
        ),
    ]
