# Generated by Django 4.1.13 on 2025-11-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_job_attachment_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='marketing_j_job_id_ebcf42_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='marketing_j_status_967ab8_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='marketing_j_created_63a34f_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_completion', 'Pending Completion'), ('pending_allocation', 'Pending Allocation'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
