# Generated by Django 4.1.13 on 2025-11-10 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0004_remove_job_marketing_j_job_id_ebcf42_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='process_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='process_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending_completion', 'Pending Completion'), ('pending_allocation', 'Pending Allocation'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('processing_queue', 'Processing Queue'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='pending_completion', max_length=32),
        ),
    ]
