# Generated by Django 4.1.13 on 2025-11-05 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import writer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0004_remove_job_marketing_j_job_id_ebcf42_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_file', models.FileField(blank=True, null=True, upload_to=writer.models.writer_upload_path)),
                ('final_copy', models.FileField(blank=True, null=True, upload_to=writer.models.writer_upload_path)),
                ('associate_file', models.FileField(blank=True, null=True, upload_to=writer.models.writer_upload_path)),
                ('final_summary', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_submission', to='marketing.job')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writer_submission',
            },
        ),
    ]
